name: "Test Project"
scenario_sets:
- name: electricity_energy_demand
  description: 'Hourly electricity demand of transport model'
- name: trips_energy_demand
  description: 'Hourly trips of EVs from origin of transport model'
narrative_sets:
- name: sheduled
  description: 'BLABLA'
# ------------------------------------------------
region_definitions:
# shared understanding of regions within the modelled area (e.g. GB)
- name: lad_uk_2016
  description: 'Local Authority Districts (data from 2016, unchanged since 2009)'
  filename: lad_2016_uk_simplified.shp
# ------------------------------------------------
interval_definitions:
# shared understanding of time intervals within a year
- name: annual
  description: 'Single interval for whole year'
  filename: annual_intervals.csv
- name: hourly
  description: 'Every hour in a year'
  filename: hourly_intervals.csv
- name: daily
  description: 'One day in a year'
  filename: daily_intervals.csv
# ------------------------------------------------
units: units.txt
# ------------------------------------------------
scenarios:
# given input data, required values for every year of a model run
- name: et_demand_baseline
  description: 'Baseline GWh of EV'
  scenario_set: electricity_energy_demand
  facets:
  - name: electricity
    filename: et_electricity.csv
    spatial_resolution: lad_uk_2016
    temporal_resolution: daily
    units: GWh
- name: et_trips_baseline
  description: 'Baseline number of EV trips'
  scenario_set: trips_energy_demand
  facets:
  - name: trips
    filename: et_trips.csv
    spatial_resolution: lad_uk_2016
    temporal_resolution: daily
    units: number
# ------------------------------------------------
narratives:
- name: sheduled
  description: 'Sheduled EV charging regime'
  filename: et_sheduled.yml
  narrative_set: et_module_narratives
- name: unsheduled
  description: 'Unsheduled EV charging regime'
  filename: et_unsheduled.yml
  narrative_set: et_module_narratives