decision_module: ''
description: Run et_module
name: et_module
narratives:
  sheduled:
  - Sheduled EV charging regime
  - Unsheduled EV charging regime
scenarios:
  transport_energy_demand: et_demand_baseline
sos_model: et_module
stamp: '2017-11-07T14:15:00+00:00'
timesteps:
- 2015
- 2020
- 2050
