decision_module: ''
description: Run et_module
name: et_module_unsheduled
narratives:
  et_module_narratives:
  - unsheduled
scenarios:
  transport_energy_demand: et_demand_baseline
sos_model: et_module
stamp: '2017-11-07T14:15:00+00:00'
timesteps:
- 2015
- 2020
- 2050
