decision_module: ''
description: Run et_module
name: et_module_sheduled
narratives:
  et_module_narratives:
  - sheduled
scenarios:
  electricity_energy_demand: et_demand_baseline
  trips_energy_demand: et_trips_baseline
sos_model: et_module
stamp: '2017-11-07T14:15:00+00:00'
timesteps:
- 2020
strategies: []
